const fs = require('node:fs');
const path = require('node:path');
const uglify = require('uglify-js');
const root = path.join(__dirname, '..');
const pkg = require('../package.json');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const write = (p, s) => fs.writeFileSync(path.join(root, p), s);
const strip = s => s.replace(/^[ \t]*\/\*[:#][^*]*\*\/\s*(\n)?/gm, '').replace(/\/\*[:#][^*]*\*\//gm, '');
write('bits/31_version.js', `exports.version = '${pkg.version}';\n`);
const bits = fs.readdirSync(path.join(root, 'bits')).filter(p => p.endsWith('.js')).sort().map(p => 'bits/' + p);
const source = bits.map(read).join('').replace(/[\r\x1a]/g, '');
write('cfb.flow.js', source);
write('cfb.js', strip(source));
const excluded = new Set(['bits/08_blob.js', 'bits/04_base64.js', 'bits/05_buf.js', 'bits/98_exports.js']);
const auxiliary = [read('misc/xlscfb.js'), ...bits.filter(p => !excluded.has(p)).map(read)].join('').replace(/[\r\x1a]/g, '').split('\n').filter(l => !l.includes('DO_NOT_EXPORT_CFB')).join('\n');
write('xlscfb.flow.js', auxiliary);
write('xlscfb.js', strip(auxiliary));
fs.mkdirSync(path.join(root, 'dist'), {recursive:true});
write('dist/cfb.js', strip(source));
write('dist/xlscfb.js', auxiliary);
write('dist/LICENSE', read('LICENSE'));
const minified = uglify.minify({'cfb.js': strip(source)}, {fromString:true,compress:false,mangle:{screw_ie8:false},output:{screw_ie8:false,preamble:source.split('\n')[0]},outSourceMap:'cfb.min.js',sourceMapUrl:'cfb.min.map'});
if (minified.error) throw minified.error;
write('dist/cfb.min.js', minified.code);
write('dist/cfb.min.map', minified.map);
